### ISSUE TITLE
Compiling and executing problem

### ISSUE THREAD

**Issue by JaimeAlvarez18** [juanmanzanero/fastest-lap#10]
-Hello! I have compiled with cmake the project, but at the time I try to run it, I get this message:

make[2]: *** No hay ninguna regla para construir el objetivo 'thirdparty/lib/liblapack.so', necesario para 'lib/libfastestlapc.so/.  Alto.
make[1]: *** [CMakeFiles/Makefile2:273: src/main/c/CMakeFiles/fastestlapc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Any idea how to solve it?

**Comment by juanmanzanero** [comment]
Hello Jaime,

Can you please specify what Linux version are you using and which compilers?

Also, can you copy here the `CMakeCache.txt` file?

**Comment by JaimeAlvarez18** [comment]
I'm using Ubuntu 9.4.0-1ubuntu1~20.04.1 (it's a virtual machine).
python 3.8.10
When I try to know the gcc and g++ compilers it says and with fortran as well :
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 Here is the CMakeCache.txt:
[CMakeCache.txt](https://github.com/juanmanzanero/fastest-lap/files/8585173/CMakeCache.txt)

**Comment by juanmanzanero** [comment]
Can you try to install the latest compilers via "sudo apt-get install gcc" ?
