### ISSUE TITLE
Energy limits

### ISSUE THREAD

**Issue by dfamonteiro** [juanmanzanero/fastest-lap#12]
Allowing the user to set a maximum energy limit for a lap (i.e. fuel limit per lap) could make this simulation tool very useful for racing series such as Indycar and Formula E.

Setting energy limits and power limits to each individual tire could also produce lap simulations that could tell us more about how drivers change their driving style in order to make the tires last.

Thank you for building this simulation tool!

**Comment by juanmanzanero** [comment]
Hello @dfamonteiro ! 

Energy limits are coming along. The code is ready and two tests (one for engine limit, and other for tire limits) were added to the continuous integration, but it is not still included into the python world. I just found it slows down things (a laptime is roughly 3 times slower). I will investigate this in the future, but for the time being I will live with it. (It does not affect the performance without energy limits.)

![Screenshot 2022-06-08 at 20 33 15](https://user-images.githubusercontent.com/26557659/172695907-e0c3f9f2-cb04-477c-8c41-990e93f66226.png)
