### ISSUE TITLE
Unable to run circuit_preprocessor in Windows 10

### ISSUE THREAD

**Issue by pierre-trott** [juanmanzanero/fastest-lap#17]
Hello, Thanks for sharing this great work and making it available on Windows!

I have an issue when trying to run the circuit_preprocessor in Python (Windows 10 - PyCharms).
When I try to run your example script, I get the following error:

![2022-06-27_08h47_58](https://user-images.githubusercontent.com/33380319/175876799-3d0b93fe-4474-4b55-8bf4-c0e8162edce4.png)

`c_lib.circuit_preprocessor(c_options);
OSError: [WinError -529697949] Windows Error 0xe06d7363`

I am able to run optimal_laptime.py without any problem.

I was thinking it could be the paths could be the issue. What is the source of these relative paths I have to put in?
If not, any ideas what it could be?

Thanks in advance!

**Comment by pierre-trott** [comment]
Python console is not giving a different output:

**Comment by juanmanzanero** [comment]
Ah, could be. Yes, you should run the script from the folder where it is located (examples/python/circuit_preprocessor)

**Comment by pierre-trott** [comment]
Ah yes, my bad.

Thank you for your help!

**Comment by juanmanzanero** [comment]
No problem. If you ever process any new circuit feel free to add it to the repository so that others can benefit. Cheers
