### ISSUE TITLE
fastest-lap v0.5 for windows runtime issue

### ISSUE THREAD

**Issue by fambr** [juanmanzanero/fastest-lap#39]
Hello,
congrats on your work.
I've been testing latest version binaries on windows through the python interface and it appears there may be a an issue with some missing dependencies related to coinmumps-3.dll.

![image](https://user-images.githubusercontent.com/95291048/212091560-d67ba23d-319c-4856-bac7-ff619385177d.png)

The machine used for the test does not have any fortran compiler installed. Repeating the test on another pc with Intel Fortran does not show the problem, so I would guess there may be need of any runtime to be installed. 
Tried a few of the ones in https://www.intel.com/content/www/us/en/developer/articles/tool/compilers-redistributable-libraries-by-version.html with no success.

Any help would be appreciated.
Francesco

**Comment by juanmanzanero** [comment]
Hello. Can you please try earlier versions? Is this specific to v0.5?

Thank you!

**Comment by fambr** [comment]
Thanks for prompt reply.

Tests on all previous versions (v0.1->v0.4) are showing the same issue.

**Comment by juanmanzanero** [comment]
Can you please try something?

Try donwloading [ipopt](https://github.com/coin-or/Ipopt/releases/download/releases%2F3.14.10/Ipopt-3.14.10-win64-msvs2019-md.zip), and execute `ipopt.exe` (located in the `bin` folder). Please tell me if you see the same error

**Comment by fambr** [comment]
> Can you please try something?
> 
> Try donwloading [ipopt](https://github.com/coin-or/Ipopt/releases/download/releases%2F3.14.10/Ipopt-3.14.10-win64-msvs2019-md.zip), and execute `ipopt.exe` (located in the `bin` folder). Please tell me if you see the same error

Execution of ipopt.exe is successful:
![image](https://user-images.githubusercontent.com/95291048/212115903-ef9741d3-82ea-4aad-8953-6b1142726d5c.png)

**Comment by juanmanzanero** [comment]
Looks like the problem is on the way I have compiled and linked the libraries. I will try to take a look

**Comment by juanmanzanero** [comment]
What python are you using? Can you try an anaconda3 shell?

**Comment by juanmanzanero** [comment]
I have uploaded a fresh compilation [here](https://github.com/juanmanzanero/fastest-lap/releases/download/v0.5/fastest-lap-w10-x64-msvc2022-v0.5-b.zip).


If this does not work, can you paste [these files](https://github.com/juanmanzanero/fastest-lap/files/10405417/tests.zip) in the `bin` folder, the `database` folder too, and run `fastest-lap-tests.exe`?

**Comment by fambr** [comment]
> What python are you using? Can you try an anaconda3 shell?

Using Python 3.9.13 in anaconda3 shell.

**Comment by fambr** [comment]
> I have uploaded a fresh compilation [here](https://github.com/juanmanzanero/fastest-lap/releases/download/v0.5/fastest-lap-w10-x64-msvc2022-v0.5-b.zip).
> 
> If this does not work, can you paste [these files](https://github.com/juanmanzanero/fastest-lap/files/10405417/tests.zip) in the `bin` folder, paste the [database](https://github.com/juanmanzanero/fastest-lap/tree/main/database) folder there too, and run `fastest-lap-tests.exe`?

New compilation is showing is still showing the issue for me but tests are essentially successful:
![image](https://user-images.githubusercontent.com/95291048/212276467-2e3bef6a-4c24-4507-a3e9-2acba35d8cda.png)

[fastest-lap-tests.log](https://github.com/juanmanzanero/fastest-lap/files/10409738/fastest-lap-tests.log)

I don't know the difference between the test suite and python interface but I suspect all this may be related to any conflict on my specific setup.

**Comment by juanmanzanero** [comment]
Ok, then runing ipopt.exe works the same as working fastest-lap-tests.exe. The problem is that mumps (this library was directly downloaded from [ipopt](https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.14.10)) indeed needs the Fortran OneAPI runtime libraries:

- Dump of file coinmumps-3.dll

> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     libiomp5md.dll
>     libifcoremd.dll
>     libmmd.dll
>     svml_dispmd.dll
>     KERNEL32.dll
>     VCRUNTIME140.dll
>     api-ms-win-crt-heap-l1-1-0.dll
>     api-ms-win-crt-stdio-l1-1-0.dll
>     api-ms-win-crt-environment-l1-1-0.dll
>     api-ms-win-crt-filesystem-l1-1-0.dll
>     api-ms-win-crt-runtime-l1-1-0.dll
>     api-ms-win-crt-string-l1-1-0.dll
>     api-ms-win-crt-time-l1-1-0.dll
>     api-ms-win-crt-utility-l1-1-0.dll
>     api-ms-win-crt-convert-l1-1-0.dll

- Dump of file libfastestlapc-0.5.dll

> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     ipopt-3.dll
>     coinmumps-3.dll
>     MSVCP140.dll
>     KERNEL32.dll
>     VCRUNTIME140_1.dll
>     VCRUNTIME140.dll
>     api-ms-win-crt-math-l1-1-0.dll
>     api-ms-win-crt-heap-l1-1-0.dll
>     api-ms-win-crt-stdio-l1-1-0.dll
>     api-ms-win-crt-convert-l1-1-0.dll
>     api-ms-win-crt-time-l1-1-0.dll
>     api-ms-win-crt-string-l1-1-0.dll
>     api-ms-win-crt-runtime-l1-1-0.dll

Can you please try to locate all those libraries (starting with `api-ms-win-crt-*.dll`) and make sure they are on the environment `PATH`?

**Comment by juanmanzanero** [comment]
Question: when does this problem happen? After "import fastest_lap", or after calling "optimal_laptime"?

Can you try the following, open an Anaconda shell in the `bin` directory and run

```python
import ctypes
lib = ctypes.CDLL("ipopt-3.dll")
libmumps = ctypes.CDLL("coinmumps-3.dll")
libmumps.dmumps_c()
```

and tell me the output you get?

**Comment by fambr** [comment]
> Question: when does this problem happen? After "import fastest_lap", or after calling "optimal_laptime"?

The error is happening after "import fastest_lap"

> Can you try the following, open an Anaconda shell in the `bin` directory and run
> 
> ```python
> import ctypes
> lib = ctypes.CDLL("ipopt-3.dll")
> libmumps = ctypes.CDLL("coinmumps-3.dll")
> libmumps.dmumps_c()
> ```
> 
> and tell me the output you get?
Here is what I get from the python shell:

![image](https://user-images.githubusercontent.com/95291048/212284648-17a8568e-380b-4631-8dca-9ddf1548272f.png)
then
![image](https://user-images.githubusercontent.com/95291048/212284893-c4add210-4e87-481a-8914-800e993d3e02.png)
and
![image](https://user-images.githubusercontent.com/95291048/212285016-c378803a-610b-4016-88aa-fd9ce18e3642.png)

**Comment by juanmanzanero** [comment]
OK, do you mind opening an issue [here](https://github.com/coin-or/Ipopt/issues), showing that you are not able to load their libraries (with the error in `lib = ctypes.CDLL("ipopt-3.dll")` it suffices), and ask them which version of the intel oneAPI are they using to build their libraries? Maybe then download their corresponding runtime version (and uninstall the ones you have previously installed)

**Comment by fambr** [comment]
> 

Sure, I will do.
Thanks for your support.

Francesco

**Comment by fambr** [comment]
Hello Juan,

I had the chance to run some additional tests on windows machines not having fortran installed and all of them have shown the same (or similar) issue when loading the library.

After some investigation I've been able to workaround the issue  patching
`v0.5\include\fastest_lap.py` by having variable `libname` referring to the full path of the dll

![image](https://user-images.githubusercontent.com/95291048/213863005-79897392-acec-4c2f-afba-ad8fdb357f58.png)

I'm not sure it is correct, but then I realized this is also done in `v0.5\examples\python\fastest_lap.py`.

Incidentally, I noticed the python example is referring to v0.1 and may be not up to date when executed from the latest release.

I hope this findings will help you with the project.

Regards,
Francesco

**Comment by juanmanzanero** [comment]
Hi Francesco,

Very nice catch! In fact it seems something I have experienced way a long time ago, but it seems I didn't remember it. It is very nice that you found it. I have re-uploaded the release with your corrections. It would be great if you can download it as it is and perform a quick system test if you have the time.

Anyway, thank you very much for this investigation!

Cheers

**Comment by juanmanzanero** [comment]
I have deleted the fastest_lap.py under `examples/`. It should not be there, but it looks like I've forgot to delete from a very old test I made.

**Comment by fambr** [comment]
Hi Juan,
I can confirm that the test of the published release was successful.

Thanks.
Francesco

**Comment by juanmanzanero** [comment]
Thank you for your time Francesco
