### ISSUE TITLE
1-simple lap errors

### ISSUE THREAD

**Issue by przkop** [juanmanzanero/fastest-lap#40]
Hello Juan,
I'm struggling with basics, can not even do simple lap per example due to errors.
I have downloaded fastest lap v.05, extracted to new folder. I'm using Windows 10 and IDLE shell 3.11.1 Here is what I get:

import sys,os,inspect
sys.path.append("/Users/Przemek/Desktop/fastest-lap/examples/python")
import fastest_lap
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import fastest_lap
  File "C:\Users/Przemek/Desktop/fastest-lap/examples/python\fastest_lap.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by juanmanzanero** [comment]
This is not a problem with fastest-lap, it's just that you shall install matplotlib (a python module to visualise and plot): https://matplotlib.org

**Comment by przkop** [comment]
Juan I'm sorry but still I'm getting errors, extracted fastest lap folder is in directory

import sys,os,inspect
sys.path.append("/C:/Users/Przemek/PycharmProjects/pythonProject/fastest-lap/examples/python")
import fastest_lap
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import fastest_lap
ModuleNotFoundError: No module named 'fastest_lap'
